# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js Version 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install npm dependencies
      run: npm ci
    - name: Install node Package Manager yarn
      run: yarn install
    - name: Check Codestyle with eslint
      run: npm run ng lint
    - name: Run Jest Unit Tests
      run: npm run test

